# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3aaad421892e6c4da5e6c9cfb168e139f588c97dc1daebfc476fbce1fd7f97bf9050a4f1b88c7992725d1894d9b6371c1734098a38608d6715cf6c8f556d524

test:
  secret_key_base: a10762077044ba00684701ecbd46030c8271de49fa20c8c8f04fa4e18f39abbd7eda5f0dc0978462b65bc566d387f231d1fcae356c7533c4a2e3cfdef42e59b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
